# Generated by Django 2.1.5 on 2019-01-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_site', '0005_auto_20190129_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
                ('surname', models.CharField(default=None, max_length=60)),
                ('fDepartment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Department')),
                ('fRole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
