# Generated by Django 2.1.5 on 2019-01-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fRole',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_site.Role'),
        ),
    ]
