# Generated by Django 2.1.5 on 2019-01-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_frole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fRole',
        ),
    ]
