# Generated by Django 2.1.5 on 2019-01-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roleaccess', '0001_initial'),
        ('users', '0003_remove_user_frole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fRole',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roleaccess.Role'),
        ),
    ]
