# Generated by Django 2.1.5 on 2019-02-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_frole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fRole',
        ),
    ]
