# Generated by Django 2.1.5 on 2019-02-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_like', models.BooleanField()),
                ('fGrade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Grade')),
                ('fQuestion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Question')),
                ('fUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('fAnswer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='answers.Answer')),
                ('fGrade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Grade')),
                ('fUserExpert', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
