# Generated by Django 2.1.5 on 2019-01-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='fQuestion',
        ),
    ]
