# Generated by Django 2.1.5 on 2019-01-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0001_initial'),
        ('answers', '0002_remove_answer_fquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='fQuestion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Question'),
        ),
    ]
