# Generated by Django 2.1.5 on 2019-01-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_answer_fquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='fGrade',
        ),
        migrations.RemoveField(
            model_name='review',
            name='fGrade',
        ),
    ]
