# Generated by Django 2.1.5 on 2019-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20190211_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_like',
            field=models.BooleanField(null=True),
        ),
    ]
