# Generated by Django 2.1.5 on 2019-01-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0002_grade'),
        ('answers', '0004_auto_20190131_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='fGrade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Grade'),
        ),
        migrations.AddField(
            model_name='review',
            name='fGrade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Grade'),
        ),
    ]
