# Generated by Django 2.1.5 on 2019-02-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_auto_20190131_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='fGrade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Grade'),
        ),
    ]
