# Generated by Django 2.1.5 on 2019-02-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'department',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'grade',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('hint', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('department', models.ManyToManyField(to='allactions.Department')),
            ],
            options={
                'db_table': 'question',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'section',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('fSection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Section')),
            ],
            options={
                'db_table': 'stage',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='fStage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Stage'),
        ),
    ]
