# Generated by Django 2.1.5 on 2019-01-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0012_auto_20190131_1514'),
        ('allactions', '0003_remove_question_fstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fStep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Stage'),
        ),
    ]
