# Generated by Django 2.1.5 on 2019-01-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0005_remove_question_fstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('fSection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Section')),
            ],
            options={
                'db_table': 'stage',
            },
        ),
    ]
