# Generated by Django 2.1.5 on 2019-01-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0006_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fStep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Stage'),
        ),
    ]
