# Generated by Django 2.1.5 on 2019-02-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0007_question_fstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(default=None),
        ),
    ]
