# Generated by Django 2.1.5 on 2019-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0008_question_hint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='fStep',
            new_name='fStage',
        ),
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.ManyToManyField(to='allactions.Department'),
        ),
    ]
