# Generated by Django 2.1.5 on 2019-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0009_auto_20190201_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
