# Generated by Django 2.1.5 on 2019-01-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_like', models.BooleanField()),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('fAnswer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Answer')),
            ],
            options={
                'db_table': 'expert_review',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('fSection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Section')),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='fStep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Step'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='fGrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Grade'),
        ),
        migrations.AddField(
            model_name='answer',
            name='fGrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Grade'),
        ),
        migrations.AddField(
            model_name='answer',
            name='fQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Question'),
        ),
    ]
