# Generated by Django 2.1.5 on 2019-01-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_like', models.BooleanField()),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_expert', models.IntegerField()),
                ('fAnswer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Answer')),
            ],
            options={
                'db_table': 'expert_review',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('fSection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Section')),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='grade',
            table='grade',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permission',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AddField(
            model_name='question',
            name='fStep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Step'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='fGrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Grade'),
        ),
        migrations.AddField(
            model_name='answer',
            name='fGrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Grade'),
        ),
        migrations.AddField(
            model_name='answer',
            name='fQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Question'),
        ),
    ]
