# Generated by Django 2.1.5 on 2019-01-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_answer_fuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertreview',
            name='fAnswer',
        ),
        migrations.RemoveField(
            model_name='expertreview',
            name='fGrade',
        ),
        migrations.DeleteModel(
            name='ExpertReview',
        ),
    ]
