# Generated by Django 2.1.5 on 2019-01-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20190130_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('fAnswer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Answer')),
                ('fGrade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Grade')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
