# Generated by Django 2.1.5 on 2019-01-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20190129_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='fUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_site.User'),
        ),
    ]
