# Generated by Django 2.1.5 on 2019-01-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_frole'),
        ('my_site', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fUserExpert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
