# Generated by Django 2.1.5 on 2019-01-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_answer_fuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fRole',
        ),
        migrations.AlterField(
            model_name='answer',
            name='fUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
