# Generated by Django 2.1.5 on 2019-01-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_review_fuserexpert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='fGrade',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fQuestion',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fUser',
        ),
        migrations.RemoveField(
            model_name='review',
            name='fAnswer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='fGrade',
        ),
        migrations.RemoveField(
            model_name='review',
            name='fUserExpert',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
