# Generated by Django 2.1.5 on 2019-01-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_fdepartment'),
        ('my_site', '0005_auto_20190129_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('fAnswer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Answer')),
                ('fGrade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_site.Grade')),
                ('fUserExpert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'expert_review',
            },
        ),
    ]
