# Generated by Django 2.1.5 on 2019-01-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_auto_20190130_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
