# Generated by Django 2.1.5 on 2019-01-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_remove_answer_fquestion'),
        ('my_site', '0007_delete_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='fStep',
        ),
        migrations.RemoveField(
            model_name='step',
            name='fSection',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
