# Generated by Django 2.1.5 on 2019-01-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0001_initial'),
        ('my_site', '0008_auto_20190130_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='fSection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='allactions.Section'),
        ),
    ]
