# Generated by Django 2.1.5 on 2019-01-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_frole'),
        ('my_site', '0009_step_fsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
