# Generated by Django 2.1.5 on 2019-01-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0010_auto_20190131_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
