# Generated by Django 2.1.5 on 2019-01-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0003_remove_question_fstep'),
        ('my_site', '0011_delete_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Stage',
        ),
        migrations.AlterModelTable(
            name='stage',
            table='stage',
        ),
    ]
